### ISSUE TITLE
can't load package no Go files in

### ISSUE THREAD

**Issue by rojomisin** [cpliakas/aws-sam-golang-example#4]
i had to add the ellipsis on go 1.13 os x
`go get github.com/cpliakas/aws-sam-golang-example/...`

**Comment by cpliakas** [comment]
Thanks for reporting this!

After thinking about this further, this project is used more as a starting point. So the common workflow will be to fork the repository and then clone it via git so you can build on top of it for your own purposes. I will modify the README to reflect that.

**Comment by cpliakas** [comment]
So, I definitely need to figure out the forking workflow before changing the instructions.

At your suggestion, I made the package `go get`-able. I also updated the README instructing people to use `go get github.com/cpliakas/aws-sam-golang-example/...`.
